modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/TeamFelnull/IWasi/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "iwasiguns"
version = "${version}"
displayName = "IWasi Guns"
authors = "MORIMORI0317, Alfort121R"
credits = "FelNull developers"
description = '''
The ikisugi gun mod...
'''
#logoFile = ""

[[dependencies.iwasiguns]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwasiguns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwasiguns]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"